name: noted
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.1
  go_router: ^11.1.2
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  fluttertoast: ^8.2.2
  share_plus: ^7.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_native_splash: ^2.3.3
  rename: ^3.0.0
  
flutter_native_splash:
  color: "#ffffff"
  image: assets/img/launcher_icon.png
  color_dark: "#121212"
  image_dark: assets/img/launcher_icon_dark.png

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/launcher_icon.png"
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/img/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
