// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDK30wFITCxIfVYv65iyaWhMzcRaEbMqcw',
    appId: '1:800241205879:web:66e730920ddedb98c47c72',
    messagingSenderId: '800241205879',
    projectId: 'flutter-riverpod-todo',
    authDomain: 'flutter-riverpod-todo.firebaseapp.com',
    storageBucket: 'flutter-riverpod-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqvSSu2r1bL5g1KtQRVUAFNU1LdWo6Gco',
    appId: '1:800241205879:android:2af6d46565b78fd1c47c72',
    messagingSenderId: '800241205879',
    projectId: 'flutter-riverpod-todo',
    storageBucket: 'flutter-riverpod-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoRelJwhTryoeo1VurhKRatq8bj76VAbM',
    appId: '1:800241205879:ios:45c966322e83251ec47c72',
    messagingSenderId: '800241205879',
    projectId: 'flutter-riverpod-todo',
    storageBucket: 'flutter-riverpod-todo.appspot.com',
    iosBundleId: 'com.example.riverpodFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoRelJwhTryoeo1VurhKRatq8bj76VAbM',
    appId: '1:800241205879:ios:e4b750337afc2a1ec47c72',
    messagingSenderId: '800241205879',
    projectId: 'flutter-riverpod-todo',
    storageBucket: 'flutter-riverpod-todo.appspot.com',
    iosBundleId: 'com.example.riverpodFirebase.RunnerTests',
  );
}
